title: The Raspberry Pi Guide
email: j.w.jolles@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A collection of tutorials to help set up and work with your Raspberry Pi
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://raspberrypi-guide.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jollewjolles
github_username:  jollejolles
remote_theme:  pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap
include:
  - _docs
logo: "/assets/images/Raspberrypi-guide-logo.jpg"
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
footer_content: "If you use find any of the information provided on this website useful it would be great to <a href=\"http://raspberrypi-guide.github.io/contact\">hear from you</a> and please consider <a href=\"http://raspberrypi-guide.github.io/paper\">citing the paper</a>! All rights reserved &copy; 2021 Jolle Jolles. Website built using Jekyll and the <a href=\"https://github.com/pmarsceill/just-the-docs\">Just the Docs</a> theme.</a>"
disqus-shortname : animpi
comment-post: https://docs.google.com/forms/d/e/1FAIpQLSe9F17myVLU52_B4UEdupm_Hfx5xXgTpVqgQyarNEQueNdM-A
comment-read: https://docs.google.com/spreadsheets/d/1oLR8u7rrr4PW6FzmIHx1sUS0mUSQVJnetLeTqdmpjlc
comment-post-fields: [entry.148489506, entry.599174399, entry.1990599000, entry.1482663308]
guestbook-post: https://docs.google.com/forms/d/e/1FAIpQLSfzPwfnqdqbreqY87rnRMAVJy0ctKFvVkYI4ehuDt8yUsswHw
guestbook-read: https://docs.google.com/spreadsheets/d/1WvAZYJaKXP1_5F64bS77EfdDcloTOpcSDsqz5HOAtHc
guestbook-post-fields: [entry.1188818118, entry.1863550937]
