title: The Raspberry Pi Guide
email: j.w.jolles@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A collection of detailed guides for working with the Raspberry Pi.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://raspberrypi-guide.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jollewjolles
github_username:  jollejolles
remote_theme:  pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
include:
  - _docs
logo: "/assets/images/Raspberrypi-guide-logo.png"
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
footer_content: "If you use find any of the information provided on this website useful it would be great to <a href=\"http://raspberrypi-guide.github.io/contact\">hear from you</a> and please consider <a href=\"http://raspberrypi-guide.github.io/paper\">citing the paper</a>! All rights reserved &copy; 2021 Jolle Jolles. Website built using Jekyll and the <a href=\"https://github.com/pmarsceill/just-the-docs\">Just the Docs</a> theme.</a>"
